export const standStraight = {
  humanRotation: 0,
  headRotation: 0,
  foreUpperArmRotation: 180,
  foreLowerArmRotation: 0,
  foreHandRotation: 0,
  hindUpperArmRotation: 180,
  hindLowerArmRotation: 0,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -20,
  foreLowerLegRotation: 0,
  foreFootRotation: 70,
  hindUpperLegRotation: -20,
  hindLowerLegRotation: 0,
  hindFootRotation: 70,
  offsetX: 0,
  offsetY: 0,
  
  borderX0: -40,
  borderX1: 40,
  borderY0: -120,
  borderY1: 180,
};

export const standReady = {
  humanRotation: 350,
  headRotation: 0,
  foreUpperArmRotation: 150,
  foreLowerArmRotation: 40,
  foreHandRotation: 0,
  hindUpperArmRotation: 190,
  hindLowerArmRotation: 30,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 15,
  foreLowerLegRotation: -30,
  foreFootRotation: 75,
  hindUpperLegRotation: -20,
  hindLowerLegRotation: -15,
  hindFootRotation: 88,
  
  offsetX: 0,
  offsetY: 5,
  borderX0: -80,
  borderX1: 80,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride1 = {
  humanRotation: 353,
  headRotation: 2,
  foreUpperArmRotation: 184,
  foreLowerArmRotation: 24,
  foreHandRotation: 8,
  hindUpperArmRotation: 174,
  hindLowerArmRotation: 27,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -3,
  foreLowerLegRotation: -19,
  foreFootRotation: 69,
  hindUpperLegRotation: 30,
  hindLowerLegRotation: -87,
  hindFootRotation: 66,

  offsetX: 0,
  offsetY: 2,
  borderX0: -100,
  borderX1: 100,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride2 = {
  humanRotation: 353,
  headRotation: 2,
  foreUpperArmRotation: 204,
  foreLowerArmRotation: 24,
  foreHandRotation: 8,
  hindUpperArmRotation: 142,
  hindLowerArmRotation: 24,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -26,
  foreLowerLegRotation: -1,
  foreFootRotation: 76,
  hindUpperLegRotation: 45,
  hindLowerLegRotation: -71,
  hindFootRotation: 57,

  offsetX: 0,
  offsetY: 2,
  borderX0: -100,
  borderX1: 100,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride3 = {
  humanRotation: 353,
  headRotation: 2,
  foreUpperArmRotation: 204,
  foreLowerArmRotation: 38,
  foreHandRotation: 8,
  hindUpperArmRotation: 150,
  hindLowerArmRotation: 34,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -26,
  foreLowerLegRotation: -48,
  foreFootRotation: 74,
  hindUpperLegRotation: 18,
  hindLowerLegRotation: -13,
  hindFootRotation: 67,

  offsetX: 0,
  offsetY: 10,
  borderX0: -100,
  borderX1: 100,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride4 = {
  humanRotation: 353,
  headRotation: 2,
  foreUpperArmRotation: 173,
  foreLowerArmRotation: 38,
  foreHandRotation: 8,
  hindUpperArmRotation: 160,
  hindLowerArmRotation: 34,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 6,
  foreLowerLegRotation: -62,
  foreFootRotation: 56,
  hindUpperLegRotation: -5,
  hindLowerLegRotation: -15,
  hindFootRotation: 74,

  offsetX: 0,
  offsetY: 2,
  borderX0: -100,
  borderX1: 100,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride5 = {
  humanRotation: 353,
  headRotation: 2,
  foreUpperArmRotation: 154,
  foreLowerArmRotation: 38,
  foreHandRotation: 6,
  hindUpperArmRotation: 180,
  hindLowerArmRotation: 34,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 40,
  foreLowerLegRotation: -62,
  foreFootRotation: 80,
  hindUpperLegRotation: -31,
  hindLowerLegRotation: -13,
  hindFootRotation: 90,

  offsetX: 0,
  offsetY: 5,
  borderX0: -100,
  borderX1: 100,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride6 = {
  humanRotation: 354,
  headRotation: 2,
  foreUpperArmRotation: 144,
  foreLowerArmRotation: 38,
  foreHandRotation: 6,
  hindUpperArmRotation: 190,
  hindLowerArmRotation: 34,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 20,
  foreLowerLegRotation: -21,
  foreFootRotation: 80,
  hindUpperLegRotation: -40,
  hindLowerLegRotation: -20,
  hindFootRotation: 70,

  offsetX: 0,
  offsetY: 10,
  borderX0: -100,
  borderX1: 100,
  borderY0: -120,
  borderY1: 180,
};

export const runStride1 = {
  humanRotation: 345,
  headRotation: 0,
  foreUpperArmRotation: 140,
  foreLowerArmRotation: 60,
  foreHandRotation: 0,
  hindUpperArmRotation: 200,
  hindLowerArmRotation: 40,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 30,
  foreLowerLegRotation: -50,
  foreFootRotation: 80,
  hindUpperLegRotation: -40,
  hindLowerLegRotation: -50,
  hindFootRotation: 70,
  
  offsetX: 0,
  offsetY: 12,
  borderX0: -100,
  borderX1: 120,
  borderY0: -120,
  borderY1: 180,
};